### ISSUE TITLE
Shocking Behaviour

### ISSUE THREAD

**Issue by jdubhub** [lpke/powerline-bakery#1]
My wife Karen went there. They didnt have any muffins and there was no manager for her to yell at.

**Comment by lpke** [comment]
@jdubhub Shocking indeed. No doubt Karen has already struck us down on all her socials. Will work on a fix ;P

**Comment by jdubhub** [comment]
@lpke suggestion for fix... have a "there can only be one Karen" fight to the death Josh Swain style....
